# Generated by Django 3.2.4 on 2021-06-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='meta_description',
            field=models.CharField(help_text='Content for description meta tag', max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='meta_keywords',
            field=models.CharField(help_text='Comma-delimited set of SEO keywords for meta tag', max_length=255, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='photo',
            field=models.ImageField(null=True, upload_to='static/users_photos/'),
        ),
    ]
