# Generated by Django 3.2.4 on 2021-06-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210628_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
