# Generated by Django 3.2.4 on 2021-06-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_usermodel_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/users_photos/'),
        ),
    ]
