# Generated by Django 3.2.4 on 2021-06-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210628_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
