<<<<<<< HEAD
# Generated by Django 3.2.4 on 2021-07-13 21:59

from django.conf import settings
=======
# Generated by Django 3.2.4 on 2021-06-30 13:42

>>>>>>> ebdc74252cb9889a844949a51698184cb16ee221
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
        ('user', '0002_remove_profil_slug'),
>>>>>>> ebdc74252cb9889a844949a51698184cb16ee221
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWithFileField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('file', models.FileField(blank=True, null=True, upload_to='static/uploads/', verbose_name='Fichier')),
=======
>>>>>>> ebdc74252cb9889a844949a51698184cb16ee221
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('slug', models.SlugField(help_text='Unique value for product page URL, created from name.', unique=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-delimited set of SEO keywords for meta tag', max_length=255, null=True, verbose_name='Meta Keywords')),
                ('meta_description', models.CharField(blank=True, help_text='Content for description meta tag', max_length=255, null=True, verbose_name='Meta Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
<<<<<<< HEAD
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile', verbose_name='User profile')),
>>>>>>> ebdc74252cb9889a844949a51698184cb16ee221
            ],
            options={
                'verbose_name': 'Upload',
                'verbose_name_plural': 'Uploads',
                'db_table': 'uploads',
            },
        ),
    ]
